language: rust
sudo: required
dist: trusty
addons:
    apt:
        packages:
            - libssl-dev

cache: cargo
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly

before_cache: |
    if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
        RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install --force cargo-tarpaulin
    fi

script:
- cargo clean
- cargo build --verbose
- cargo test  --verbose

branches:
  only:
    - master

after_success: |
    if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
        cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
    fi

